kind: Service
apiVersion: v1
metadata:
  name: lab.helidon
  labels:
    app: lab.helidon
spec:
  type: ClusterIP
  selector:
    app: lab.helidon
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lab.helidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab.helidon
  template:
    metadata:
      labels:
        app: lab.helidon
        version: v1
    spec:
      containers:
      - name: lab.helidon
        image: lab.helidon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
